name: gnn_mis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas
  - ca-certificates
  - certifi
  - cffi
  - cpuonly
  - expat
  - freetype
  - jpeg
  - lcms2
  - libblas
  - libcblas
  - libgfortran
  - libgfortran5
  - liblapack
  - liblapacke
  - libpng
  - libtiff
  - libuv
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - ninja
  - openjpeg
  - openssl
  - pip
  - pycparser
  - python=3.11
  - pytorch-mutex
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - attrs==23.2.0
      - charset-normalizer==3.3.2
      - deprecated==1.2.14
      - dimod==0.12.14
      - dwave-neal==0.6.0
      - dwave-samplers==1.2.0
      - filelock==3.14.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - idna==3.7
      - jinja2==3.1.4
      - joblib==1.4.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.3
      - numpy==1.26.4
      - psutil==5.9.8
      - pyparsing==3.1.2
      - pyqubo==1.4.0
      - requests==2.31.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - six==1.16.0
      - sympy==1.12
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - tqdm==4.66.4
      - typing-extensions==4.11.0
      - urllib3==2.2.1
      - wrapt==1.16.0
      - yarl==1.9.4